version: '3'

services:
    node:
      container_name: nodeapp
      build: ./server
      ports:
        - "5000:5000"
      depends_on:
        - db
      networks:
        - plantbarter_network
      env_file:
        - .env #the .env variable gets overriden by the host, in this case it's AWS. 
        
    db: 
        container_name: db
        build: ./server/database
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports: 
          - "4306:3306"
        volumes:
          - "./data:/var/lib/mysql"
        networks:
          - plantbarter_network
        environment:
          MYSQL_ROOT_PASSWORD: password

networks:
    plantbarter_network:
      driver: bridge   
