version: '3'

services:
    node:
      container_name: nodeapp
      build: ./server
      ports:
        - "5000:5000"
      depends_on:
        - db
      networks:
        - plantbarter_network
      environment:
        PORT: 5000
        MYSQLPORT: 3306
        DATABASE_HOST: db
        DATABASE_USER: root
        DATABASE_PASSWORD: MYSUPERSECRETPASSWORD
        DATABASE_TABLE: plantbarter
        NODE_ENV: production
        
    db: 
        container_name: db
        build: ./server/database
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports: 
          - "4306:3306"
        volumes:
          - "./data:/var/lib/mysql"
        networks:
          - plantbarter_network
        environment:
          MYSQL_ROOT_PASSWORD: password

networks:
    plantbarter_network:
      driver: bridge   
